name: Deploy Kubernetes Manifests

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy-manifests:
    name: Apply K8s Manifests to GKE
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set GKE Credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: YOUR_GKE_CLUSTER_NAME
          location: YOUR_CLUSTER_LOCATION  # e.g., us-central1
          project_id: YOUR_PROJECT_ID

      - name: Apply cert-manager manifests
        run: |
          kubectl apply -f manifests/cert-manager.yaml
          kubectl apply -f manifests/clusterissuer.yaml
          kubectl apply -f manifests/ingress.yaml
